import requests

url = "https://yowaimo.in/StreamFlexTv/playlist.php?name=SFBRMYCG&token=e1265dd4bee0302fd0fc7d50"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36",
    "Accept": "*/*"
}

r = requests.get(url, headers=headers, timeout=20)

print(r.status_code)
print(r.text[:200])

with open("playlist.m3u", "w", encoding="utf-8") as f:
    f.write(r.text)
